// Auto-generated by Gemini. Based on openapi.json

export interface AssetFilterParams {
  user_id?: number | null;
  title?: string;
  category_id?: number;
  price_min?: number;
  price_max?: number;
  only_favorites?: boolean;
  page?: number;
  page_size?: number;
}

export interface AssetFeedItem {
  id: number;
  name: string;
  price: string;
  discount: string;
  cover_picture: string | null;
  category_id: number | null;
  category_name: string | null;
  average_rating: number | null;
  review_count: number;
  is_favorite: boolean;
}

export interface AssetFeedResponse {
  total: number;
  items: AssetFeedItem[];
}

export interface AssetPictureRead {
  id: number;
  data: string;
  is_cover: boolean;
}

export interface AssetRead {
  id: number;
  user_id: number;
  license_type_id: number;
  category_id: number | null;
  name: string;
  description: string | null;
  price: string;
  discount: string;
  youtube_link: string | null;
  pictures: AssetPictureRead[];
  created_at: string;
  updated_at: string;
}

export interface UserCreate {
  first_name: string;
  last_name: string;
  username: string;
  email: string;
  password: string;
  active: boolean;
  user_type_id: number;
  created_at: string;
  updated_at: string;
}

export interface UserRead {
  id: number;
  first_name: string;
  last_name: string;
  username: string;
  email: string;
  active: boolean;
  user_type_id: number;
  created_at: string;
  updated_at: string;
}

export interface LicenseTypeRead {
    id: number;
    name: string;
    description: string | null;
    can_use_commercially: boolean;
    can_modify: boolean;
    can_resell: boolean;
    can_sublicense: boolean;
    requires_attribution: boolean;
    created_at: string;
    updated_at: string;
}

export interface CategoryRead {
    id: number;
    name: string;
    parent_id: number | null;
    created_at: string;
    updated_at: string;
}

export interface CategoryReadWithChildren extends CategoryRead {
    children?: CategoryReadWithChildren[];
}

export interface AssetPictureInput {
    data: string;
    is_cover: boolean;
}

export interface AssetCreate {
    user_id: number;
    license_type_id: number;
    name: string;
    category_id?: number | null;
    description?: string | null;
    price?: string;
    discount?: string;
    youtube_link?: string | null;
    pictures?: AssetPictureInput[];
}

export interface ReviewCreate {
    asset_id: number;
    user_id: number;
    rate: number;
    message: string | null;
}

export interface ReviewRead {
    id: number;
    asset_id: number;
    user_id: number;
    rate: number;
    message: string | null;
    created_at: string;
}

export interface UserTypeResponse {
    id: number;
    type: string;
    created_at: string;
    updated_at: string;
}

export interface LoginRequest {
    email: string;
    password: string;
}
